# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IGListDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'IGListKit', '3.4.0'
  # Pods for IGListDemo

end
